name: example
description: A new Flutter project.

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  jugger:
    path: ../jugger

dev_dependencies:
  build_runner: ^2.1.1
  jugger_generator:
    path: ../jugger_generator
  test: ^1.16.0