name: example

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  jugger:
    path: ../jugger

dev_dependencies:
  build_runner: ^2.1.7
  build_test: ^2.1.5
  jugger_generator:
    path: ../jugger_generator
