name: jugger
description: Compile-time dependency injection for Dart and Flutter.
version: 1.1.0-alpha
author: ivk1800
homepage: https://github.com/ivk1800/jugger.dart

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  meta: ^1.1.7