name: jugger
description: >
  Annotations for the jugger_generator.
  This package does nothing without jugger_generator too.
version: 2.4.0-dev.2
homepage: https://github.com/ivk1800/jugger.dart

environment:
  sdk: ">=2.12.0 <3.0.0"