name: flutter_example
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  flutter_lints: 1.0.4
  freezed_annotation: 1.1.0
  jugger:
    path: ../jugger
  meta: 1.7.0

dev_dependencies:
  build_runner: 2.1.7
  freezed: 1.1.1
  jugger_generator:
    path: ../jugger_generator