name: my_injector
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  jugger:
    path: ../../../jugger
  example1:
    path: ../app
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.7.2
  jugger_generator:
    path: ../../../jugger_generator