name: my_injector
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  jugger: ^1.1.0-alpha
  example1:
    path: ../app
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.7.2
  jugger_generator:
    path: ../../../jugger_generator