name: jugger_generator
description: >
  Compile-time dependency injection for Dart and Flutter.
  Jugger's feature is that it generates boilerplate code.
version: 3.1.1
homepage: https://github.com/ivk1800/jugger.dart

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  analyzer: ^5.7.1
  build: ^2.3.1
  code_builder: ^4.5.0
  collection: ^1.15.0
  dart_style: ^2.0.0
  jugger: ^3.0.0
  source_gen: ^1.2.7
  quiver: ^3.0.0

dev_dependencies:
  lint: 2.1.2