name: jugger_generator
description: Generates dependency injection code using the jugger package.
version: 1.1.0+4-alpha
homepage: https://github.com/ivk1800/jugger.dart

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  analyzer: ^3.0.0
  build: ^2.0.0
  code_builder: ^4.0.0
  collection: ^1.15.0
  crypto: ^3.0.0
  dart_style: ^2.0.0
  jugger:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger
      ref: 9e9f4e9beb08951b37ec8592147ba52979c33d30
  quiver: ^3.0.0