name: jugger_generator
description: >
  Compile-time dependency injection for Dart and Flutter.
  Jugger's feature is that it generates boilerplate code.
version: 3.1.0
homepage: https://github.com/ivk1800/jugger.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^5.2.0
  build: ^2.0.0
  code_builder: ^4.1.0
  collection: ^1.15.0
  crypto: ^3.0.0
  dart_style: ^2.0.0
  jugger: ^3.0.0
  quiver: ^3.0.0

dev_dependencies:
  lint: 1.10.0