name: jugger_generator
description: Generates dependency injection code using the jugger package.
version: 1.1.0+4-alpha
author: ivk1800
homepage: https://github.com/ivk1800/jugger.dart

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  analyzer: ^1.1.0
  build: ^1.6.3
  built_value: ^7.0.0
  code_builder: ^3.3.0
  collection: ^1.15.0
  dart_style: ^1.3.14
  jugger:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger
      ref: 02cb9197b758cd89457d71c2b4c1daab4d92477c
  meta: ^1.3.0