name: jugger_generator
description: Generates dependency injection code using the jugger package.
version: 1.1.0-alpha
author: ivk1800
homepage: https://github.com/ivk1800/jugger.dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  jugger: 1.1.0-alpha
  build: ^1.2.1
  code_builder: ^3.2.0
  dart_style: ^1.3.3
  quiver: ^2.0.5
  meta: ^1.1.7
  analyzer: ^0.39.1