name: jugger_generator
description: Generates dependency injection code using the jugger package.
version: 1.1.0+2-alpha
author: ivk1800
homepage: https://github.com/ivk1800/jugger.dart

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  collection: ^1.15.0
  jugger:
    path: ../jugger
  build: ^1.6.3
  code_builder: ^3.2.0
  dart_style: ^1.3.14
  quiver: ^3.0.0
  meta: ^1.3.0
  analyzer: ^1.1.0