name: jugger_generator
description: Compile-time dependency injection for Dart and Flutter.
version: 2.0.0
homepage: https://github.com/ivk1800/jugger.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^3.0.0
  build: ^2.0.0
  code_builder: ^4.0.0
  collection: ^1.15.0
  crypto: ^3.0.0
  dart_style: ^2.0.0
  jugger: ^2.0.0
  quiver: ^3.0.0