name: Dart CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        sdk: [ 2.17.0 ]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Run tests
        run: |
          cd tests
          dart test
