name: Dart CI

on:
  pull_request:
    paths:
      - "jugger/**"
      - "jugger_generator/**"
      - "tests/**"
      - ".github/workflows/dart_ci.yaml"

jobs:
  dart:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        sdk: [ 3.0.0 ]
        dir: ['jugger', 'jugger_generator', 'tests']
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install Dependencies
        working-directory: ${{ matrix.dir }}
        run: dart pub get

      - name: Format
        working-directory: ${{ matrix.dir }}
        run: dart format --set-exit-if-changed .

      - name: Run tests
        working-directory: tests
        run: dart test

      - name: Run generation for tests
        working-directory: tests
        run: dart run build_runner build
