name: Dart CI

on:
  push:
    paths:
      - "jugger/**"
      - "jugger_generator/**"
      - "tests/**"
      - ".github/workflows/dart_ci.yaml"

  pull_request:
    paths:
      - "jugger/**"
      - "jugger_generator/**"
      - "tests/**"
      - ".github/workflows/dart_ci.yaml"

jobs:
  dart:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        sdk: [
          2.12.0,
          2.13.0,
          2.14.0,
          2.15.0,
          2.16.0,
          2.17.0,
          2.18.0,
          2.19.0,
        ]
        dir: ['jugger', 'jugger_generator', 'tests']
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install Dependencies
        working-directory: ${{ matrix.dir }}
        run: dart pub get

      - name: Format
        working-directory: ${{ matrix.dir }}
        run: dart format --set-exit-if-changed .

      - name: Run tests
        working-directory: tests
        run: dart test

      - name: Run generation for tests
        working-directory: tests
        run: dart run build_runner build
